Clean up deploy and update scripts

diff --git a/.local/bin/deploy-dotfiles b/.local/bin/deploy-dotfiles
--- a/.local/bin/deploy-dotfiles
+++ b/.local/bin/deploy-dotfiles
@@ -1,20 +1,20 @@
 #!/bin/sh
 
-for var in '$DOTFILES_REPO' $($DOTFILES_REPO/.local/lib/dotfiles/scripts/fix_paths); do
-	if eval "[ -z $var ]"; then
+for var in DOTFILES_REPO $($DOTFILES_REPO/.local/lib/dotfiles/scripts/fix_paths 2>/dev/null); do
+	if eval '[ -z $'"$var ]"; then
 		echo "$var is not set.  Aborting."
 		exit 1
 	fi
 done
-if [ -n "$1" ]; then
-	cd "$DOTFILES_REPO" || exit 1
-	git pull
-fi
+[ -n "$1" ] && cd "$DOTFILES_REPO" && git pull
 files=$($DOTFILES_REPO/.local/lib/dotfiles/scripts/print_dotfiles)
 echo "$files" | rsync --ignore-missing-args --files-from=- "$DOTFILES_REPO" ~
-cd "$HOME" && $DOTFILES_REPO/.local/lib/dotfiles/scripts/fix_paths deploy $files
+if ! cd "$HOME"; then
+	echo "Cannot cd into HOME.  Aborting."
+	exit 1
+fi
+$DOTFILES_REPO/.local/lib/dotfiles/scripts/fix_paths deploy $files
 $DOTFILES_REPO/.local/lib/dotfiles/scripts/init_config deploy
 systemctl --user daemon-reload
-pidof i3 > /dev/null 2>&1 && i3-msg reload > /dev/null 2>&1
+pidof i3 > /dev/null 2>&1 && i3-msg reload > /dev/null 2>&1 && echo "Reloaded i3"
 echo "Done."
-exit 0
