Better deploy/update scripts

diff --git a/.local/bin/deploy-dotfiles b/.local/bin/deploy-dotfiles
--- a/.local/bin/deploy-dotfiles
+++ b/.local/bin/deploy-dotfiles
@@ -1,26 +1,20 @@
-#!/bin/bash
+#!/bin/sh
 
-if [ -z "$DOTFILES_REPO" ]; then
-	echo 'DOTFILES_REPO is not set. Aborting.'
-	exit 1
+for var in '$DOTFILES_REPO' $($DOTFILES_REPO/.local/lib/dotfiles/scripts/fix_paths); do
+	if eval "[ -z $var ]"; then
+		echo "$var is not set.  Aborting."
+		exit 1
+	fi
+done
+if [ -n "$1" ]; then
+	cd "$DOTFILES_REPO" || exit 1
+	git pull
 fi
-if [ -z "$XDG_RUNTIME_DIR" ]; then
-	echo 'XDG_RUNTIME_DIR is not set. Aborting.'
-	exit 1
-fi
-cd $DOTFILES_REPO
-[ -n "$1" ] && git pull
-files=$(find $DOTFILES_REPO/ -path $DOTFILES_REPO/.git -prune -o \( \! -name 'README\.md' -type f -printf "%P\n" \))
-sed_files=$(grep -El '/path/to/home|/path/to/xdg_runtime_dir' $(echo "$files" | grep -vE '(update|deploy)-dotfiles'))
-sed -i -e's@/path/to/home@'"$HOME"'@g' -e's@/path/to/xdg_runtime_dir@'"$XDG_RUNTIME_DIR"'@g' $sed_files
-echo "$files" | rsync --ignore-missing-args --files-from=- $DOTFILES_REPO ~
-sed -i -e's@'"$HOME"'@/path/to/home@g' -e's@'"$XDG_RUNTIME_DIR"'@/path/to/xdg_runtime_dir@g' $sed_files
-
-[ ! -f $HOME/.Xresources ] && cp $DOTFILES_REPO/.local/lib/dotfiles/Xresources $HOME/.Xresources
-[ ! -f $HOME/.config/autorandr/settings.ini ] && cp $DOTFILES_REPO/.local/lib/dotfiles/autorandr-settings.ini $HOME/.config/autorandr/settings.ini
-[ -n "$(find /sys/class/power_supply -name 'BAT*')" ] && sed -i -e's@#order += "battery all"@order += "battery all"@' ~/.config/i3status/config
-cat $DOTFILES_REPO/.local/lib/dotfiles/dconf | dconf load /
-
+files=$($DOTFILES_REPO/.local/lib/dotfiles/scripts/print_dotfiles)
+echo "$files" | rsync --ignore-missing-args --files-from=- "$DOTFILES_REPO" ~
+cd "$HOME" && $DOTFILES_REPO/.local/lib/dotfiles/scripts/fix_paths deploy $files
+$DOTFILES_REPO/.local/lib/dotfiles/scripts/init_config deploy
 systemctl --user daemon-reload
-pidof i3 && i3-msg reload
+pidof i3 > /dev/null 2>&1 && i3-msg reload > /dev/null 2>&1
+echo "Done."
 exit 0
diff --git a/.local/bin/update-dotfiles b/.local/bin/update-dotfiles
--- a/.local/bin/update-dotfiles
+++ b/.local/bin/update-dotfiles
@@ -1,20 +1,15 @@
-#!/bin/bash
+#!/bin/sh
 
-if [ -z "$DOTFILES_REPO" ]; then
-	echo 'DOTFILES_REPO is not set. Aborting.'
-	exit 1
-fi
-if [ -z "$XDG_RUNTIME_DIR" ]; then
-	echo 'XDG_RUNTIME_DIR is not set. Aborting.'
-	exit 1
-fi
-files=$(find $DOTFILES_REPO/ -path $DOTFILES_REPO/.git -prune -o \( \! -name 'README\.md' -type f -printf "%P\n" \))
-echo "$files" | rsync --ignore-missing-args --files-from=- ~ $DOTFILES_REPO
-
-cd $DOTFILES_REPO
-sed_files=$(echo "$files" | grep -vE '(update|deploy)-dotfiles')
-sed -i -e's@'"$HOME"'@/path/to/home@g' -e's@'"$XDG_RUNTIME_DIR"'@/path/to/xdg_runtime_dir@g' $sed_files
-sed -i -e's@order += "battery all"@#order += "battery all"@' $DOTFILES_REPO/.config/i3status/config
-
+for var in '$DOTFILES_REPO' $($DOTFILES_REPO/.local/lib/dotfiles/scripts/fix_paths); do
+	if eval "[ -z $var ]"; then
+		echo "$var is not set.  Aborting."
+		exit 1
+	fi
+done
+files=$($DOTFILES_REPO/.local/lib/dotfiles/scripts/print_dotfiles)
+echo "$files" | rsync --ignore-missing-args --files-from=- ~ "$DOTFILES_REPO"
+cd "$DOTFILES_REPO" && $DOTFILES_REPO/.local/lib/dotfiles/scripts/fix_paths update $files
+$DOTFILES_REPO/.local/lib/dotfiles/scripts/init_config update
+echo "Done."
 git status
 exit 0
